name: remeanflow
channels:
  - conda-forge
dependencies:
  - python=3.9.19
  - pytorch==2.1.0
  - torchaudio==2.1.0
  - torchvision==0.16.0
  - numpy=1.26.4
  - accelerate=0.29.2
  - matplotlib
  - timm=0.9.16
  - transformers=4.40.2
  - ipykernel